-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-05-26 02:09:17 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE categorii (
    id_categorie     INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nume_categorie   varchar(30) NOT NULL
);

ALTER TABLE categorii AUTO_INCREMENT=1;

ALTER TABLE categorii ADD CONSTRAINT categorii_nume_categorie_uk UNIQUE ( nume_categorie );

CREATE TABLE comenzi (
    id_comanda      INTEGER  AUTO_INCREMENT PRIMARY KEY NOT NULL,
    data_comanda    DATE NOT NULL,
	adresa			varchar(500) NOT NULL,
	valoare			DECIMAL(8, 2) NOT NULL,
	livrata			BOOLEAN NOT NULL DEFAULT 0,	
    id_utilizator   INTEGER NOT NULL
);

ALTER TABLE comenzi AUTO_INCREMENT=1;

CREATE TABLE cos (
    id_produs       INTEGER NOT NULL,
	cantitate		INTEGER NOT NULL,
    id_utilizator   INTEGER NOT NULL
);

CREATE TABLE detalii_utilizatori (
    nume_utilizator      varchar(50) NOT NULL,
    prenume_utilizator   varchar(50) NOT NULL,
    adresa_utilizator    varchar(500) NOT NULL,
    telefon_utilizator   varchar(15) NOT NULL,
	admin_utilizator	 bool NOT NULL,
    id_utilizator        INTEGER NOT NULL
);


CREATE UNIQUE INDEX detalii_utilizatori__idx ON
    detalii_utilizatori (
        id_utilizator
    ASC );

CREATE TABLE produse (
    id_produs          INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nume_produs        varchar(30) NOT NULL,
    pret_produs        DECIMAL(8, 2) NOT NULL,
    descriere_produs   varchar(500),
    imagine_produs     varchar(500),
    id_categorie       INTEGER NOT NULL
);

ALTER TABLE produse AUTO_INCREMENT=1;

ALTER TABLE produse ADD CONSTRAINT produse_pret_ck CHECK ( pret_produs >= 0 );

ALTER TABLE produse ADD CONSTRAINT produse_nume_produs_uk UNIQUE ( nume_produs );

CREATE TABLE produse_din_comanda (
    id_produs_comanda   INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    id_produs           INTEGER NOT NULL,
	cantitate			INTEGER NOT NULL,
	pret				DECIMAL(8, 2) NOT NULL,
    id_comanda          INTEGER NOT NULL
);

ALTER TABLE produse_din_comanda AUTO_INCREMENT=1;


CREATE TABLE utilizatori (
    id_utilizator       INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_utilizator     varchar(50) NOT NULL,
    email_utilizator    varchar(100) NOT NULL,
    parola_utilizator   varchar(100) NOT NULL
);

ALTER TABLE utilizatori AUTO_INCREMENT=1;

ALTER TABLE utilizatori ADD CONSTRAINT email_ck CHECK ( email_utilizator LIKE '%@%.%' );

ALTER TABLE utilizatori ADD CONSTRAINT utilizatori_email_uk UNIQUE ( email_utilizator );

ALTER TABLE utilizatori ADD CONSTRAINT utilizatori_user_uk UNIQUE ( user_utilizator );

ALTER TABLE produse
    ADD CONSTRAINT categorii_produse_fk FOREIGN KEY ( id_categorie )
        REFERENCES categorii ( id_categorie );

ALTER TABLE produse_din_comanda
    ADD CONSTRAINT comenzi_produse_din_comanda_fk FOREIGN KEY ( id_comanda )
        REFERENCES comenzi ( id_comanda );

ALTER TABLE detalii_utilizatori
    ADD CONSTRAINT detalii_utilizatori_fk FOREIGN KEY ( id_utilizator )
        REFERENCES utilizatori ( id_utilizator );

ALTER TABLE cos
    ADD CONSTRAINT produse_cos_fk FOREIGN KEY ( id_produs )
        REFERENCES produse ( id_produs );

ALTER TABLE produse_din_comanda
    ADD CONSTRAINT produse_produse_din_comanda_fk FOREIGN KEY ( id_produs )
        REFERENCES produse ( id_produs );

ALTER TABLE comenzi
    ADD CONSTRAINT utilizatori_comenzi_fk FOREIGN KEY ( id_utilizator )
        REFERENCES utilizatori ( id_utilizator );

ALTER TABLE cos
    ADD CONSTRAINT utilizatori_cos_fk FOREIGN KEY ( id_utilizator )
        REFERENCES utilizatori ( id_utilizator );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
